### ISSUE TITLE
Plan for local environment?

### ISSUE THREAD

**Issue by djKooks** [aguyyala/real-time-analytics-dashboard#1]
Hello
First, thanks for your work. I'm studying on data engineering, and your project is being a great resource. Thanks for that.
By the way, it looks like it is planned for deploying to AWS. Do you have a plan or guide to make this work in local environment?

**Comment by aguyyala** [comment]
Hey, thanks! Yes this is actually running on AWS. Do you mean Local Machine by Local Environment or on-premise cluster? It should techincally work the same no matter the box on which you run. You might run into some installation/configuration issues but eventually it should work the same. But yeah as of now I don't have anything that run on Local Machine. I'll try to do it if I get some time later on.

**Comment by djKooks** [comment]
@aguyyala okay, what I mean was local environment. Thanks for reply~
